services:
  app:
    image: hm-be
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8000:8000'
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/code:rw
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: compose.yaml
  redis:
    image: redis:alpine
    env_file:
      - .env
    ports:
      - '6379:6379'
