services:
  app:
    image: hm-be
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - ./src:/core/src:rw
    depends_on:
      - redis
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: compose.yaml
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    command: ['redis-server']
